doc fix
TracecatHQ/tracecat pull request #13
Opened 2024-03-26 18:51 UTC by aboutphilippe

2024-03-26 20:00 UTC, topher-lo commented
Thanks a ton for the PR! Will review and get back to you. Can you confirm this works on your machine?

Congrats on being our first public PR. We should probably send you some Tracecat merch

2024-03-26 20:17 UTC, aboutphilippe commented
I can confirm the API talks to db and frontend talks to API properly.

<img width="1400" alt="image" src="https://github.com/TracecatHQ/tracecat/assets/7622544/2240f26c-6787-4427-b7a4-d798a587e421">

2024-03-26 20:39 UTC, daryllimyt commented
Hey, thanks so much for this PR! I will look at this in a bit as well, just debugging our staging env atm

2024-03-27 21:41 UTC, daryllimyt requested changes
LGTM! Just one change in the `docker compose up` step - don't need the -f flag. Thanks so much for this :)

2024-03-27 21:41 UTC, daryllimyt commented on docs/installation.mdx
> +docker compose -f up
```suggestion
docker compose up
```

2024-03-27 21:51 UTC, merged