Temporal Docker Compose Implementation
TracecatHQ/tracecat pull request #184
Opened 2024-06-21 14:40 UTC by LuedTek

## Description & Overview
Docker compose extension that sets up temporal. Installation guide should be updated to include the command ```-f docker-compose.temporal.yml``` for prod and ```-f docker-compose.temporal.yml -f docker-compose.temporal.dev.yml``` for dev.

Documentation involving the installation changes have not been made in this PR. 

## Related Tickets & Documents
To run: 

prod:
```docker compose -f docker-compose.yml -f docker-compose.temporal.yml up```

dev: 
```docker compose -f docker-compose.yml -f -f docker-compose.dev.yml -f docker-compose.temporal.yml -f docker-compose.temporal.dev.yml up```

2024-06-21 16:17 UTC, topher-lo reviewed
WIP

2024-06-21 23:41 UTC, daryllimyt commented
# Final changes
- Add Temporal services into Tracecat's docker compose. You can now run `docker compose up` to spin up a fully working instance.
- Set Temporal services to log level `warn`
- Update conftests
- Remove extraneous compose extensions

2024-06-22 00:00 UTC, topher-lo commented on .env.example
> +TRACECAT__DB_URI=postgresql+psycopg://${TRACECAT__POSTGRES_USER}:${TRACECAT__POSTGRES_PASSWORD}@host.docker.internal:5432/postgres
Please fix?

2024-06-22 00:01 UTC, topher-lo requested changes
postgres uri still has docker internal

2024-06-22 00:02 UTC, daryllimyt commented
Nice catch, fixed

2024-06-22 00:05 UTC, topher-lo approved these changes
LGTM

2024-06-22 00:05 UTC, merged