Webhook endpoint for synchronous execution and return workflow final_context
TracecatHQ/tracecat pull request #279
Opened 2024-07-28 14:04 UTC by mattdurant

## Description

This is so that you can call a webhook in Tracecat to perform some actions and receive as a response the final_context object from the workflow.

My current use case is an outgoing webhook in Teams instead of a full bot implementation, so I can send a message in a channel to @ChatOps with a command, parse the command in the workflow and then do some work and the final_context is returned.  In this case, a chat message indicating success or failure.

## Related Tickets & Documents
N/A

## Screenshots/Recordings

N/A

## Steps to QA

Test by calling a webhook, but add /wait to the URL, the response will return once the workflow is finished and contain the final_context of the workflow.

## [optional] What gif best describes this PR?

2024-07-28 14:53 UTC, topher-lo commented on tracecat/api/app.py
> +async def incoming_webhook_Wait(
```suggestion
async def incoming_webhook_wait(
```

2024-07-28 15:04 UTC, daryllimyt requested changes

2024-07-28 15:04 UTC, daryllimyt commented on tracecat/api/app.py
> +async def incoming_webhook_Wait(
style: snake case

2024-07-28 15:04 UTC, daryllimyt commented on tracecat/api/app.py
> +    """
could we update the docstring here to reflect that this endpoint behaves differently from the regular one?

2024-07-28 15:52 UTC, mattdurant commented on tracecat/api/app.py
> +async def incoming_webhook_Wait(
Out of curiosity, why would wait be capitalized here? I've not seen snake case have any words capitalized like this before.

2024-07-28 16:21 UTC, mattdurant commented on tracecat/api/app.py
> +async def incoming_webhook_Wait(
Oh man, ignore me, I completely misread Chris' review and thought he suggested capitalizing Wait.  I didn't realize I committed it that way...

2024-07-28 21:47 UTC, daryllimyt commented on tracecat/api/app.py
> +async def incoming_webhook_Wait(
no worries :)

2024-07-28 21:48 UTC, daryllimyt approved these changes
LGTM

2024-07-29 14:27 UTC, topher-lo commented
Will delay this PR for next week's release while we rework the API routers and add tests this week.

2024-07-29 14:27 UTC, topher-lo reviewed
Wait for API work to complete this week

2024-07-30 20:01 UTC, mattdurant commented
@daryllimyt @topher-lo based on the conflict here, I think you guys did a big refactoring during the same time, I think I should close this PR and start clean make the 2-3 changes to enable this again and re-submit, agreed?

2024-07-31 00:05 UTC, daryllimyt commented
> @daryllimyt @topher-lo based on the conflict here, I think you guys did a big refactoring during the same time, I think I should close this PR and start clean make the 2-3 changes to enable this again and re-submit, agreed?

Yes - I'm also aiming to close #285  so I think it makes sense to adjust it accordingly

2024-07-31 00:56 UTC, closed without merging