feat(integrations)!: Tracecat registry
TracecatHQ/tracecat pull request #404
Opened 2024-09-17 10:59 UTC by topher-lo

Related to #403

This PR introduces Tracecat Registry, which migrates all actions and integrations into a standalone python package `tracecat_registry`. Existing UDF-based integrations have also been generalized into templated actions as part of this PR.

## Breaking changes
- Registry MUST import in a package NOT subpackage or individual module
- Renamed `analyze_{ioc}` into `search_{ioc}` to differentiate search (GET) to scans (POST, wait then GET report)
- All action names have been shortened to avoid verbosity e.g. `integrations.crowdstrike.list_crowdstrike_alerts` -> `integrations.crowdstrike.list_alerts`
- Okra: Renamed `okta_user_id` arg to `user_id`
- Jira: Renamed args `atlassian_domain` to `domain`, `issue_summary` to `summary`, `issue_priority` to `priority_id`, and `issue_type` to `issue_type_id` and dropped `optional_fields` in OOTB templated action (can be cloned then edited)
- All `search_malware_sample` actions: `file_hash` arg has been shortened to `hash`
- Sentinel One: Update actions now take list of IDs as opposed to single ID. Exact match and contains match filters for get agents is now split into two separate actions

## What changed
- Rewrite UDFs into:
  - Generic wrappers of Python SDKs (`boto3`, `falconpy`, `slack-sdk`)
  - Templated actions (either of SDK wrappers or `core.http_request`)
- Move integrations dependencies from `tracecat` to `tracecat_registry`
- QA: Add simple validation test of templated actions
- Removed `.parent.parent` pathing in tests. Just use relative path (from repo path as root).

## Note
List of breaking API changes will be published alongside the next 0.11 release docs.

2024-09-20 15:07 UTC, daryllimyt requested changes
🚀 lfg

2024-09-20 15:07 UTC, daryllimyt commented on docker-compose.dev.yml
> +      - ./registry:/app/registry
Add this for prod docker compose too

2024-09-20 15:07 UTC, daryllimyt commented on registry/tracecat_registry/integrations/__init__.py
> +__version__ = "0.1.0"
```suggestion
```

2024-09-20 15:07 UTC, daryllimyt commented on tests/unit/test_registry.py
> +    yield test_module
try finally so it always cleans up

2024-09-20 15:07 UTC, daryllimyt commented on tracecat/registry.py
>      def _load_template_actions(self) -> None:
TODO: parametrize this

2024-09-20 15:07 UTC, daryllimyt commented on tracecat/registry.py
> +            file_paths.append(file_path)
nit: count maybe?

2024-09-20 15:07 UTC, daryllimyt commented on tracecat/registry.py
> +        logger.info("Running template action", action=self.definition.name)
keep as action

2024-09-20 15:11 UTC, topher-lo commented on tracecat/registry.py
> +        logger.info("Running template action", action=self.definition.name)
```suggestion
        logger.info("Running template action", action=self.definition.action)
```

2024-09-20 15:12 UTC, topher-lo commented on tracecat/registry.py
>      def _load_template_actions(self) -> None:
KK will do in next PR

2024-09-22 09:47 UTC, daryllimyt approved these changes
LGTM

2024-09-22 09:48 UTC, merged